#!/bin/sh

if [ "$1" -lt "1" ]
then
    i=`echo "$1 + 1" | bc`
    wantname="i350bb"
    check="no"
else
    i=`echo $1 - 1 | bc`
    wantname="coretemp"
    check="yes"
fi

for mon in /sys/class/hwmon/*
do
    [ -f ${mon}/name ] || continue
    name=`cat ${mon}/name`
    [ "${name}" = "${wantname}" ] || continue
    if [ "${check}" = "yes" ]
    then
        for sensor in ${mon}/temp*_label
        do
            [ "`cat $sensor`" = "Core ${i}" ] || continue
            trueinput=`echo $sensor | sed 's/_label$/_input/'`
            echo "scale = 1; `cat ${trueinput}` / 1000" | bc
            exit 0
        done
    else
        echo "scale = 1; `cat ${mon}/temp${i}_input` / 1000" | bc
        exit 0
    fi
done
echo "99.9"
exit 1
