#!/bin/bash
# Usage: tempget node
SICREGS="/proc/sicread"
[ -e "/proc/sicregs" ] && SICREGS="/proc/sicregs"
Tm=`echo 0x0cd4 > /proc/sicread; cat $SICREGS | grep "node: $1 reg (0xCD4)" | awk '{print $5}'`
Tm=$(( (Tm & 0x3FFC000) >> 14 ))
T=`echo "scale=1; $Tm / 8" | bc`
[ $T = "0" ] && T=99.9
echo $T
