#!/bin/sh
modprobe l_pcs
for mon in /sys/class/hwmon/*
do
    [ -f ${mon}/name ] || continue
    name=`cat ${mon}/name`
    [ "${name}" = "l_pcs" ] || continue
    [ "`cat ${mon}/node`" = "$1" ] || continue
    for sensor in ${mon}/temp*_label
    do
        [ "`cat $sensor`" = "Node $1 Max" -o "`cat $sensor`" = "CurrMax" ] || continue
        trueinput=`echo $sensor | sed 's/_label$/_input/'`
        echo "scale = 1; `cat ${trueinput}` / 1000" | bc
        exit 0
    done
done
echo "99.9"
exit 1
